vars:
  stage: experiments
  environment: ue1
  region: us-east-1
  aws_profile_name: experiments-admin

import:
  - catalog/ecr
  - catalog/vpc

components:
  terraform:
    ecr:
      vars:
        repository_names:
          - challenge-devops

    vpc:
      metadata:
        component: vpc
        inherits:
          - vpc/defaults
      vars:
        ipv4_primary_cidr_block: "10.111.0.0/16"
