name: Pull Request Pipeline

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      # - 'challenge-devops/**'
      - '**'
  pull_request:
    branches-ignore:
      - 'main'
    paths:
      - 'challenge-devops/**'
  workflow_dispatch:  # Allows manual triggering, useful for debugging purposes

jobs:
  test:
    if: github.ref != 'refs/heads/main' # Exclude `main` branch
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: challenge-devops
      DOCKER_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./challenge-devops
          platforms: linux/amd64
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          load: true
          push: false # Explicitly set to false for clarity

      - name: Run tests in container
        run: |
          docker run --rm \
            --env DJANGO_ENV=testing \
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} bash -c "python manage.py test"
